FROM golang:1.6.2-onbuild
MAINTAINER ProgWML6 <progwml6@gmail.com>
EXPOSE 4000
ARG FASTLY_KEY
ARG BUILD_NUMBER
ARG GIT_BRANCH
ARG GIT_COMMIT
ARG JOB_NAME
ARG BUILD_TAG
ARG BS_test
ENV FASTLY_KEY ${FASTLY_KEY}
ENV BUILD_NUMBER ${BUILD_NUMBER}
ENV GIT_BRANCH ${GIT_BRANCH}
ENV GIT_COMMIT ${GIT_COMMIT}
ENV JOB_NAME ${JOB_NAME}
ENV BUILD_TAG ${BUILD_TAG}
ENV BS_test bs2
run echo $BS_test